### PR TITLE
Update build script: add mention about NDK ver, check for valid NDK path, remove useless backslashes

### PR DESCRIPTION
**Pull request by vickyleu**
woff2 repo CmakeLists.txt not link `libbrotlicommon.so` with NDK versions below `22.0.6917172`:
```
[cmake] aarch64-linux-android/bin/ld: warning: libbrotlicommon.so, needed by scripts/sources/install/brotli/arm64-v8a/lib/libbrotlienc.so, not found (try using -rpath or -rpath-link)
[cmake] scripts/sources/install/brotli/arm64-v8a/lib/libbrotlienc.so: undefined reference to `BrotliGetDictionary'
```

Also the python script has useless backslashes inside parentheses.

### CODE REVIEW

**Comment by khoben** [comment]
Hi, @vickyleu 
`woff2` and `brotli` are compiled into static libraries (`.a`) to be assembled into single shared `libwoff2decoder.so` lib later ([here](https://github.com/khoben/woff2-android/blob/master/libwoff2dec/src/main/cpp/CMakeLists.txt#L45)).

The shared libraries shouldn`t be created ([see here](https://github.com/khoben/woff2-android/blob/master/scripts/build_ndk.py#L83)) at all, but the compiler still produces .so for brotli.

Can you specify where the linking error occurs? And what does "python script has wrong format by run command" mean?

**Comment by vickyleu** [comment]
@khoben 
python script has wrong format
```
        run(f'cmake -S {WOFF2_SOURCE_DIR} -B {WOFF2_BUILD_PATH}' \
            f' -DBUILD_SHARED_LIBS=OFF' missing backslash \
            f' -DCMAKE_INSTALL_PREFIX={WOFF2_PREFIX_PATH} -DCMAKE_BUILD_TYPE=RELEASE'missing backslash \
            
```

**Comment by vickyleu** [comment]
and woff2 official repo has compile error



```
[cmake] aarch64-linux-android/bin/ld: warning: libbrotlicommon.so, needed by scripts/sources/install/brotli/arm64-v8a/lib/libbrotlienc.so, not found (try using -rpath or -rpath-link)
[cmake] scripts/sources/install/brotli/arm64-v8a/lib/libbrotlienc.so: undefined reference to `BrotliGetDictionary'
```

It seems that the rPath for the libbrotlicommon.so library is missing

**Comment by khoben** [comment]
> @khoben 
> python script has wrong format
> ```
>         run(f'cmake -S {WOFF2_SOURCE_DIR} -B {WOFF2_BUILD_PATH}' \
>             f' -DBUILD_SHARED_LIBS=OFF' missing backslash \
>             f' -DCMAKE_INSTALL_PREFIX={WOFF2_PREFIX_PATH} -DCMAKE_BUILD_TYPE=RELEASE'missing backslash \
>             
> ```

Thanks, I got it. Those backslashes aren't needed at all inside parentheses.

**Comment by khoben** [comment]
> and woff2 official repo has compile error
> 
> 
> 
> ```
> [cmake] aarch64-linux-android/bin/ld: warning: libbrotlicommon.so, needed by scripts/sources/install/brotli/arm64-v8a/lib/libbrotlienc.so, not found (try using -rpath or -rpath-link)
> [cmake] scripts/sources/install/brotli/arm64-v8a/lib/libbrotlienc.so: undefined reference to `BrotliGetDictionary'
> ```
> 
> It seems that the rPath for the libbrotlicommon.so library is missing
> 

What operating system is on your build machine?

**Comment by vickyleu** [comment]
> > and woff2 official repo has compile error
> > ```
> > [cmake] aarch64-linux-android/bin/ld: warning: libbrotlicommon.so, needed by scripts/sources/install/brotli/arm64-v8a/lib/libbrotlienc.so, not found (try using -rpath or -rpath-link)
> > [cmake] scripts/sources/install/brotli/arm64-v8a/lib/libbrotlienc.so: undefined reference to `BrotliGetDictionary'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It seems that the rPath for the libbrotlicommon.so library is missing
> 
> What operating system is on your build machine?

MacOS 14.0 (23A344)

**Comment by khoben** [comment]
@vickyleu Can you check the build with pkg-config disabled (last commit)? I think that's the problem.

**Comment by khoben** [comment]
Just checked, it builds without problems on clean Windows 10 and Ubuntu 20 with latest Android SDK (NDK 26.1.10909125). Try to build it with the latest changes in your fork.

**Comment by vickyleu** [comment]
@khoben I've found the reason. All NDK versions below 22.0.6917172 have issues.

**Comment by vickyleu** [comment]
@khoben I've found the reason. All NDK versions below 22.0.6917172 have issues.

**Comment by khoben** [comment]
Thanks for your PR and research.

**Pull request merged**
